# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/Dev/xc7k420t_1/xc7k420t.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/Dev/xc7k420t_1/xc7k420t.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Dev/xc7k420t_1/xc7k420t.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/Dev/xc7k420t_1/xc7k420t.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/Dev/xc7k420t_1/xc7k420t.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ubuntu/Dev/xc7k420t_1/xc7k420t.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
