# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Synth 8-350}  -string {{WARNING: [Synth 8-350] instance 'eth_phy_10g_0' of module 'eth_phy_10g' requires 19 connections, but only 17 given [/media/ubuntu/cb61d42a-8b65-409a-b927-0dce7ec79991/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/mac_adapter.v:116]}}  -suppress 
create_project -in_memory -part xc7k420tffg901-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ubuntu/Dev/xc7k420t/xc7k420t.cache/wt [current_project]
set_property parent.project_path /home/ubuntu/Dev/xc7k420t/xc7k420t.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ubuntu/Dev/xc7k420t/xc7k420t.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/arbiter.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_adapter.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_arb_mux.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_async_fifo.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_async_fifo_adapter.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_demux.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_fifo.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_xgmii_rx_32.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_xgmii_rx_64.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_xgmii_tx_32.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/axis_xgmii_tx_64.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/debounce.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_mac_10g.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_mac_10g_fifo.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g_rx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g_rx_ber_mon.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g_rx_frame_sync.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g_rx_if.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g_tx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/eth_phy_10g_tx_if.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_cmd_rx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_completer.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_pkt_rx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_pkt_tx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_tlp_rc.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_tlp_rq.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_vq.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_vq_packed_cx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_vq_packed_rx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/srcs/eth_virtio_vq_packed_tx.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/eth_virtio_wrapper.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/gtwizard_common.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/gtwizard_usrclk.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/gtx_drp_mon.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/gtx_wrapper.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/new/ila_cache.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/lfsr.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/mac_adapter.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/mmcm_wrapper.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/pcie_axi_wrapper.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/pcie_config_space.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/pcie_pipe_clock.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/pcie_us_axi_master.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/shadow/pcie_us_axi_master_rd.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/shadow/pcie_us_axi_master_wr.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/shadow/pcie_us_axis_cq_demux.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/new/pcie_wrapper.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/priority_encoder.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/ptp_clock_cdc.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/ptp_tag_insert.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/ptp_ts_extract.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/pulse_merge.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/rtl/xgmii_baser_dec_64.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/imports/shadow/xgmii_baser_enc_64.v
  /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/new/top.v
}
read_ip -quiet /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc]

read_ip -quiet /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc]

read_ip -quiet /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7k420tffg901-2L -directive AlternateRoutability -no_lc -shreg_min_size 10


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
