set_property SRC_FILE_INFO {cfile:/home/ubuntu/Dev/xc7k420t/xc7k420t.srcs/constrs_1/new/top.xdc rfile:../../../xc7k420t.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA27     [get_ports CLK_100MHz[1]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC27     [get_ports CLK_100MHz[0]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16     [get_ports RESET]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ22     [get_ports LED[0]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21     [get_ports LED[1]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK21     [get_ports LED[2]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20     [get_ports LED[3]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK19     [get_ports LED[4]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ19     [get_ports LED[5]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK18     [get_ports LED[6]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18     [get_ports LED[7]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N30      [get_ports KEY[0]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y30      [get_ports KEY[1]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y29      [get_ports KEY[2]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA30     [get_ports KEY[3]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB30     [get_ports KEY[4]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB29     [get_ports KEY[5]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC30     [get_ports KEY[6]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC29     [get_ports KEY[7]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK15     [get_ports KEY3]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C29      [get_ports GPIO[ 0]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B30      [get_ports GPIO[ 1]]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D29      [get_ports GPIO[ 2]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C30      [get_ports GPIO[ 3]]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E30      [get_ports GPIO[ 4]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E29      [get_ports GPIO[ 5]]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G29      [get_ports GPIO[ 6]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F30      [get_ports GPIO[ 7]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H29      [get_ports GPIO[ 8]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G30      [get_ports GPIO[ 9]]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J29      [get_ports GPIO[10]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H30      [get_ports GPIO[11]]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K30      [get_ports GPIO[12]]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K29      [get_ports GPIO[13]]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M29      [get_ports GPIO[14]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L30      [get_ports GPIO[15]]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG30     [get_ports GPIO[16]]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M30      [get_ports GPIO[17]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG29     [get_ports GPIO[18]]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH30     [get_ports GPIO[19]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH29     [get_ports GPIO[20]]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK30     [get_ports GPIO[21]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ29     [get_ports GPIO[22]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK29     [get_ports GPIO[23]]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ28     [get_ports GPIO[24]]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK28     [get_ports GPIO[25]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ27     [get_ports GPIO[26]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ26     [get_ports GPIO[27]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK26     [get_ports GPIO[28]]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK25     [get_ports GPIO[29]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ24     [get_ports GPIO[30]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK24     [get_ports GPIO[31]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ23     [get_ports GPIO[32]]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK23     [get_ports GPIO[33]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A30      [get_ports UART_RXD]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B29      [get_ports UART_TXD]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24      [get_ports {SFP_TX_DISABLE[0]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22      [get_ports {SFP_TX_DISABLE[1]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25      [get_ports {SFP_TX_DISABLE[2]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B27      [get_ports {SFP_TX_DISABLE[3]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A23      [get_ports {SFP_RS0[0]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20      [get_ports {SFP_RS0[1]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A27      [get_ports {SFP_RS0[2]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E28      [get_ports {SFP_RS0[3]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B23      [get_ports {SFP_SDA[0]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21      [get_ports {SFP_SDA[1]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B25      [get_ports {SFP_SDA[2]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A28      [get_ports {SFP_SDA[3]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22      [get_ports {SFP_SCL[0]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20      [get_ports {SFP_SCL[1]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A26      [get_ports {SFP_SCL[2]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B28      [get_ports {SFP_SCL[3]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E8       [get_ports SFP_GTREFCLK_P[0]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E7       [get_ports SFP_GTREFCLK_N[0]]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12      [get_ports {SFP_TXP[0]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11      [get_ports {SFP_TXN[0]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12      [get_ports {SFP_RXP[0]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11      [get_ports {SFP_RXN[0]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8       [get_ports {SFP_TXP[1]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7       [get_ports {SFP_TXN[1]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10      [get_ports {SFP_RXP[1]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9       [get_ports {SFP_RXN[1]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4       [get_ports {SFP_TXP[2]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3       [get_ports {SFP_TXN[2]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6       [get_ports {SFP_RXP[2]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5       [get_ports {SFP_RXN[2]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2       [get_ports {SFP_TXP[3]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1       [get_ports {SFP_TXN[3]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E4       [get_ports {SFP_RXP[3]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3       [get_ports {SFP_RXN[3]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8       [get_ports PCIE_CLK_P]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2       [get_ports {PCIE_TXP[0]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1       [get_ports {PCIE_TXN[0]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4       [get_ports {PCIE_RXP[0]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3       [get_ports {PCIE_RXN[0]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2      [get_ports {PCIE_TXP[1]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1      [get_ports {PCIE_TXN[1]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6       [get_ports {PCIE_RXP[1]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5       [get_ports {PCIE_RXN[1]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD2      [get_ports {PCIE_TXP[2]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1      [get_ports {PCIE_TXN[2]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4      [get_ports {PCIE_RXP[2]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3      [get_ports {PCIE_RXN[2]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2      [get_ports {PCIE_TXP[3]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF1      [get_ports {PCIE_TXN[3]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6      [get_ports {PCIE_RXP[3]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5      [get_ports {PCIE_RXN[3]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21      [get_ports PCIE_RST_N]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pcie_7x_0_main_pblock_boot
add_cells_to_pblock [get_pblocks pcie_7x_0_main_pblock_boot] [get_cells -quiet [list eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_7x_0_inst]]
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {SLICE_X178Y100:SLICE_X189Y249 SLICE_X162Y200:SLICE_X177Y249}
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {DSP48_X11Y60:DSP48_X11Y99}
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {GTXE2_CHANNEL_X0Y8:GTXE2_CHANNEL_X0Y11}
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {GTXE2_COMMON_X0Y2:GTXE2_COMMON_X0Y2}
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {PCIE_X0Y0:PCIE_X0Y0}
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {RAMB18_X10Y80:RAMB18_X11Y99}
resize_pblock [get_pblocks pcie_7x_0_main_pblock_boot] -add {RAMB36_X10Y40:RAMB36_X11Y49}
set_property BOOT_BLOCK 1 [get_pblocks pcie_7x_0_main_pblock_boot]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
create_pblock clk_logic_pblock_boot
add_cells_to_pblock [get_pblocks clk_logic_pblock_boot] [get_cells -quiet [list eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/GND eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/GND_1 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/VCC eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/VCC_1 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line130 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line131 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line175 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line186 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line187 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line188 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/nolabel_line56 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_i eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_reg0_i eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_reg0_i__0 eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_reg1_i {eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_reg[0]} {eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_reg[1]} {eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_q_reg[2]} eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_pclk_s1_reg eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/pipe_rst_i]]
resize_pblock [get_pblocks clk_logic_pblock_boot] -add {SLICE_X124Y150:SLICE_X127Y199}
set_property BOOT_BLOCK 1 [get_pblocks clk_logic_pblock_boot]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pcie_7x_0_ext_mmcm_pblock_boot
add_cells_to_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] [get_cells -quiet [list eth_virtio_wrapper_inst/pcie_axi_wrapper_inst/pcie_wrapper_inst/pcie_pipe_clock_inst/mmcm2_adv_0]]
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {IN_FIFO_X0Y12:IN_FIFO_X0Y15}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {MMCME2_ADV_X0Y3:MMCME2_ADV_X0Y3}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {OUT_FIFO_X0Y12:OUT_FIFO_X0Y15}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {PHASER_IN_PHY_X0Y12:PHASER_IN_PHY_X0Y15}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {PHASER_OUT_PHY_X0Y12:PHASER_OUT_PHY_X0Y15}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {PHASER_REF_X0Y3:PHASER_REF_X0Y3}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {PHY_CONTROL_X0Y3:PHY_CONTROL_X0Y3}
resize_pblock [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot] -add {PLLE2_ADV_X0Y3:PLLE2_ADV_X0Y3}
set_property BOOT_BLOCK 1 [get_pblocks pcie_7x_0_ext_mmcm_pblock_boot]
